### ISSUE TITLE
Great work and some ref recommended

### ISSUE THREAD

**Issue by hxhc** [dario-passos/DeepLearning_for_VIS-NIR_Spectra#1]
Great work. We have tried some CNN application studies of Raman and UV spectra in our own area. But our work does not focus on the algorithms. Thanks for your sharing. By the way, we also found some interesting papers, but didn't have the ability to reproduce the results😅.  If you are interested, I truly hope you can reproduce the results, and make some thrilling insights. Thank you!

Here are the links [Convolutional neural networks for vibrational spectroscopic data analysis](https://www.sciencedirect.com/science/article/pii/S0003267016314842?via%3Dihub) and [Feature expansion by a continuous restricted Boltzmann machine for near-infrared spectrometric calibration](https://www.sciencedirect.com/science/article/pii/S0003267018300916?via%3Dihub).

**Comment by dario-passos** [comment]
Hey @hxhc 
> 
> Here are the links [Convolutional neural networks for vibrational spectroscopic data analysis](https://www.sciencedirect.com/science/article/pii/S0003267016314842?via%3Dihub) and [Feature expansion by a continuous restricted Boltzmann machine for near-infrared spectrometric calibration](https://www.sciencedirect.com/science/article/pii/S0003267018300916?via%3Dihub).

the first paper (Acquarelli et al 2017) is on my pipeline for some time now. I intend to reproduce those results using Tensorflow/Keras. The authors shared their data set and their code (in the Lasagne framework) in a bitbucket site, so that is a good starting point. The second one I didn't knew, but I'll definitely take a look. Right now I'm trying to solve a big problem related to my job ( cough cough... i.e. find a new one!! ) so it might take a while! 😅

Cheers

**Comment by hxhc** [comment]
> Hey @hxhc
> 
> > Here are the links [Convolutional neural networks for vibrational spectroscopic data analysis](https://www.sciencedirect.com/science/article/pii/S0003267016314842?via%3Dihub) and [Feature expansion by a continuous restricted Boltzmann machine for near-infrared spectrometric calibration](https://www.sciencedirect.com/science/article/pii/S0003267018300916?via%3Dihub).
> 
> the first paper (Acquarelli et al 2017) is on my pipeline for some time now. I intend to reproduce those results using Tensorflow/Keras. The authors shared their data set and their code (in the Lasagne framework) in a bitbucket site, so that is a good starting point. The second one I didn't knew, but I'll definitely take a look. Right now I'm trying to solve a big problem related to my job ( cough cough... i.e. find a new one!! ) so it might take a while! 😅
> 
> Cheers

Congrats for your new job!
  
  I am also working with my PhD thesis now, and having a hard time, indeed😂. I will also reread these papers after this period. 

Best

**Comment by dario-passos** [comment]
> Congrats for your new job!

I would realy realy like to accept your "Congrats" but I'll have to postpone that to when I actually get a new job! I'm currently still looking... Cheers
