### ISSUE TITLE
Saving pre-trained models

### ISSUE THREAD

**Issue by vfonsecad** [dario-passos/DeepLearning_for_VIS-NIR_Spectra#2]
In the Tutorial on DL optimization, after running the trials for the Bayesian Optimization, how is the trial saved to read it as

model_cnn.load_weights("regression_models/pre-trained/study_trial=156.h5")

?

**Comment by dario-passos** [comment]
Hi Valeria
in cell [17] of the regression tutorial notebook,  we define the variable "path" where we choose the folder where the models are going to be saved. The saving occurs in the  _objective(trial)_ function  (defined a bit below) by the function  

`custom_checkpointer= CustomModelCheckpoint(filepath=path+MODEL_NAME, verbose=0, save_best_only=True) `
 where
`MODEL_NAME='study_trial='+str(trial.number)+'.h5' `

So all the models that are iterated over the optimization will be saved in the folder defined in the path. The "pre-trained" folder that I'm sharing was added latter on, just as a way of sharing our pre-trained models, just in case people just wanted to explore a model and not go through the whole training process. I hope this answers your question...

**Comment by vfonsecad** [comment]
Got it, 

So change 
loaded_study = optuna.load_study(study_name="study", storage="sqlite:///study_precomputed.db")
by
loaded_study = optuna.load_study(study_name="study", storage="sqlite:///study.db")

and change
model_cnn.load_weights("regression_models/pre-trained/study_trial=156.h5")
by
model_cnn.load_weights("regression_models/study_trial={}.h5") with {} the number of your best trial


Thanks!
